### ISSUE TITLE
Only 10 posts show up on category page

### ISSUE THREAD

**Issue by kikozww** [s3bubble/Streamium-Netflix-Theme#1]
Hi, first and foremost i want to thank you for making this theme is amazing.
The problem im having is only 10 posts are showing on the category pages, and i have more than 10 posts on that category. I hope you guys help me thanks., 

**EDIT:** I fixed it, if someone wants to know, just go to Settings>Reading> and change the two first ones to what number of posts you want!

**Comment by s3bubble** [comment]
Hi kikozww,

Can you send me a link and I'll take s look.

Best Regards

Sam

**Comment by kikozww** [comment]
Hi, Sam
I already fixed it it was in settings. Thanks anyways.
Can you help with one more thing, can you add to the theme or help me out, i want to add featured image url plugin to the theme but the image doesnt show, i need to upload for my wordpress for them to work, and i want to use featured image from a url, not uploading it for my wordpress.

**Comment by s3bubble** [comment]
Hi Kikozww,

Currently the only way you can change the image is through the S3Bubble admin for the streaming theme if you are using iframes.

Best Regards

Sam

**Comment by kikozww** [comment]
Im not talking about the player, im talking about the post image, i want to add the plugin "featured image from url" which allows me to add a url instead of me uploading the featured images for the wordpress where my website is hosted.

**Comment by sobytes** [comment]
Might be worth taking a look at this.

https://neliosoftware.com/blog/use-image-url-set-featured-image/

**Comment by kikozww** [comment]
Hi, 
I tried that plugin now and it doesnt work too, the featured image of the post doesnt show up on the home page, as you can see in this image https://i.imgur.com/pvpU2QR.png the left one doesnt show the featured image because i tried that plugin and the right works because i uploaded it to the media library. I think i need to add something to the code, but i dont understand php that much.
