### ISSUE TITLE
Playlist and Home Header

### ISSUE THREAD

**Issue by Nipple4Nipple** [s3bubble/Streamium-Netflix-Theme#10]
Is It possible for you to add a TV Show episode style playlist for your theme so i could start adding tv shows with various episode into my website. Doing it manually is possible but it is very inefficient. 

And could you add the same header and menu from the homepage and place it in the the post page aswell? when my visitor click and watches videos in my website, They isn't any header menu for them to jump to other pages easily like genre or back to the main menu easily by  clicking the Top left title.

http://imgur.com/a/XtcWQ.

**Comment by Nipple4Nipple** [comment]
Make it look something like this I guess if you didn't catch what i said

http://imgur.com/a/yfB4r

**Comment by Nipple4Nipple** [comment]
Oh and 1 more thing, when the theme color is changed, when genre is opened, it no longer shows a clean transparent background instead a full colored page background covering the whole screen

http://imgur.com/a/8xUp8

**Comment by s3bubble** [comment]
Hi @Nipple4Nipple ,

Currently, you set a playlist for a series like this.

http://streamiumtheme.com/comedy/star-wars-force-awakens/

Best Regards

Sam

**Comment by Nipple4Nipple** [comment]
Hopefully you will add a playlist build in your theme since I'm using my a different embed video code from other source to place the movies

Theme is unbelievably great with constant update and improvements, Keep it up!
