### ISSUE TITLE
v2.9 update kinda broke my website

### ISSUE THREAD

**Issue by Nipple4Nipple** [s3bubble/Streamium-Netflix-Theme#11]
I love the new design you added into your latest release but the new update changed the way the theme reads and register post since i use my own custom embed code to my movies like so

http://imgur.com/a/RjVsV

Now it just shows a blank page and a buggy looking preview on the homepage. I could use the provided new added feature you provided that states "Add video URL here" but then i have to redo everything from scratch for my post.

**Comment by s3bubble** [comment]
Hi @Nipple4Nipple,

We are building this theme in conjunction with feedback from our S3bubble users so we will be making no attempt to support any other services sorry.

If an older version worked for you please stick with that.

Best Regards

Sam
