### ISSUE TITLE
Custom Post Type for videos as opposed to 'Post' post type

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#13]
Can a change or option be created for the videos to be available or converted from a post type of 'Post' to a Custom Post Type of, for example, 'Video Post'?

This will allow a site to have blog posts which are different from the Video posts. 

This would also make the theme more expandable. A video page in Streamium Netflix theme can then be selected created using a Template and selecting the page in the Settings->Reading menu to make the Front Page the Netflix style video page with customer post types and maintain the taxonomy of posts as blog posts and create a Blog page.

This also extends the functionality of the site to give the ability of to use S3Bubble videos in blog posts.

I'd like to add a Blog, but there is currently not a way to do that with the Streamium theme. Netflix maintains a separate site for it's blog, but that does not seem practical when using Wordpress.

**Comment by s3bubble** [comment]
Everything has been moved to custom post types with the new update
