### ISSUE TITLE
v10.x not showing videos and can't embed video, can't figure out how to show a video

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#16]
The "Main Video" selector does not appear to be working correctly, so i'm not sure how to either select a video or paste my video code. Either i'm doing something wrong or it doesn't work. 
![image](https://user-images.githubusercontent.com/23251123/26908058-2ac15686-4bc6-11e7-98e7-ff2f3ae6b8ab.png)

**Comment by gaborkukucska** [comment]
Same here :( ... I've added my website in s3bubble, created an app a bucket etc... nothing shows up on the list...

**Comment by s3bubble** [comment]
Hi Guys,

Can you try the following, for your videos to show in the list you need to view them at least once in S3Bubble dashboard you can click the Sync button when you are viewing a bucket that will sync all mp4 files.

You can view all your files that should show up in the list here.
https://s3bubble.com/secure/#/encoded

If nothing shows there then nothing will show in your dropdown list.

Best Regards

Sam

**Comment by gaborkukucska** [comment]
Hi Sam,

I can see the video in s3Bubble but not in website... aren't we missing something?

When I press the 'sync' button while viewing a bucket in s3bubble it actually states:

"Successfully synced 0 objects."

![image](https://user-images.githubusercontent.com/3059648/27086445-8d9980ac-5095-11e7-9e9a-55977faaa6be.png)

**Comment by s3bubble** [comment]
Hi gaborkukucska,

Whats you S3bubble username? you can send it to support@s3bubble.com if you dont want to post it here.

Best Regards

Sam

**Comment by gaborkukucska** [comment]
Thank you Sam, I've sent an email.

**Comment by s3bubble** [comment]
Hi @gaborkukucska,

Though it was worth posting the response here in case any other users run into the same problem.

When you connected your website you locked it down to a single bucket, you then created a new bucket and uploaded your media to that bucket so the api was locked on your other set bucket.

Hope that makes sense if you are going to be using multiple buckets make sure you set the bucket to all when connecting your website ;)

Best Regards

Sam

**Comment by gaborkukucska** [comment]
Ah so you're saying if I'm not a fool it works :D THANKS!

**Comment by wenotice** [comment]
whoa, this shouldn't be closed. That was not my issue. All my videos are shown in the list. When I select the video it does not associate itself with the post. It does not show that I have a selected video.

**Comment by wenotice** [comment]
My issue is fixed in v10.9
