### ISSUE TITLE
Ability to use the index.php template as a Page template

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#17]
I can no longer use the index.php template as a custom page template as it gives a blank white page. Previous to v10.x I could just copy the index.php page to a page template, then assign it to a page change some css and it works. This is no longer the case. 

I have another page as a landing page I use as the index page so the videos page needs to be some other page.

**Comment by s3bubble** [comment]
this wont be changing

**Comment by wenotice** [comment]
Since the implementation of Customer Post Types this request is not needed.
