### ISSUE TITLE
Wordpress Uploader Not Working

### ISSUE THREAD

**Issue by gaborkukucska** [s3bubble/Streamium-Netflix-Theme#19]
After updating to the current version the options to add the AWS key 'n secret for the uploader has disappeared ...

![image](https://user-images.githubusercontent.com/3059648/27086580-f642d7ac-5095-11e7-8350-86f7f457650b.png)

However it never actually worked...

![image](https://user-images.githubusercontent.com/3059648/27086632-17ec3376-5096-11e7-8182-36ffc65e7ac4.png)

**Comment by s3bubble** [comment]
You should now be able to use premium settings in the trial

**Comment by gaborkukucska** [comment]
The place to setup the key and secret is still missing from the newest theme. I can't see any new commits to the code any chance to send me the snippet ?

**Comment by gaborkukucska** [comment]
This was working till I've upgraded. It again says I need to upgrade :)


Sincerely
Gabor Kukucska
Creative Director - Buyah Media <http://www.buyahmedia.com/>
[image: Phone] +61 430 832 481

[image: Visit our website!] <http://www.buyahmedia.com/>
