### ISSUE TITLE
This is only available with the Premium package.

### ISSUE THREAD

**Issue by gaborkukucska** [s3bubble/Streamium-Netflix-Theme#20]
Does the 10 day free trial exclude some settings? The "Video Trailer", "Main Slider" and the "Multiple Videos" options are all marked unavailable.

![image](https://user-images.githubusercontent.com/3059648/27086994-2ab7aa02-5097-11e7-9057-23e39817e5c3.png)

**Comment by s3bubble** [comment]
Hi gaborkukucska,

Yes, these are only available on a premium package but we should add these during the trial we will look into adding this to the next update.

Best Regards

Sam

**Comment by gaborkukucska** [comment]
Thanks! I better pay then :)

**Comment by gaborkukucska** [comment]
This was working till I've upgraded. It again says I need to upgrade :)

**Comment by s3bubble** [comment]
Hi @gaborkukucska,

I have checked your account and you have only upgraded to the basic package $19.99 which doesn't include premium features.

https://s3bubble.com/pricing/

You will need to go back to pricing and then upgrade to premium.

Best Regards

S3Bubble

**Comment by gaborkukucska** [comment]
oh. bummer... can't really afford more at the moment. that's cool. Is the
uploader a premium feature too?


Sincerely
Gabor Kukucska
Creative Director - Buyah Media <http://www.buyahmedia.com/>
[image: Phone] +61 430 832 481

[image: Visit our website!] <http://www.buyahmedia.com/>
