### ISSUE TITLE
Improved nested menus

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#21]
The Hardcoded menus will nest the categories, but if I have nested pages, the menu does not handle this gracefully. When nested pages are added, the responsive layout compresses the entire site to the left of the menu. Any nesting in the menus should get a carrot dropdown like the other menu items Channels, TV Programs, Live Streams.

Or

Provide the ability to hide the other menu items Channels, TV Programs, Live Streams so it can be replaced by something like https://wpmegamenu.com/.

**Comment by s3bubble** [comment]
we wont be doing this

**Comment by wenotice** [comment]
I just want to be able to add a sub-item in a menu without the theme blowing up. Please re-consider handling sub-items in the menu. You are already doing it with your Custom Taxonomy items, the theme is just not handling the css properly.

**Comment by s3bubble** [comment]
Hi James,

Can we have an example of the theme blowing up please and we will look into it ;)
