### ISSUE TITLE
Streamium on mobile

### ISSUE THREAD

**Issue by gaborkukucska** [s3bubble/Streamium-Netflix-Theme#28]
On my samsung android with Chrome the share icons don't work, I also get a "This Page is in Spanish. Translate it to English." popup... :/

With its native "internet" app the films don't play when I tap the play button.

**Comment by gaborkukucska** [comment]
Also if opened via the facebook or instagram app iusers get
"Error: Request failed. Returned status of 500"

Am I doing something wrong?  This is becoming a dealbreaker for me as 80% of our traffic is mobile...

Any ideas? Thanks!

**Comment by gaborkukucska** [comment]
Sharing and back icons also not working on mobile either...

**Comment by s3bubble** [comment]
Hi Gabor,

Can you try the share and back buttons on mobile now?

Best Regards

S3Bubble

**Comment by gaborkukucska** [comment]
no still doesn't work on android with chrome
page: https://inspireflix.com/docos/elysian-dreams/




Sincerely
Gabor Kukucska
Creative Director - Buyah Media <http://www.buyahmedia.com/>
[image: Phone] +61 430 832 481

[image: Visit our website!] <http://www.buyahmedia.com/>

**Comment by s3bubble** [comment]
Hi Gabor,

Just checked on a Samsung S3 Galaxy and the back and share buttons are working which means it is probably a cache issue Google on Android caches everything to the nth degree can you try an incognito window or clear cache?

Also, we did get the translation to Spanish but that doesn't seem to be an S3Bubble issue I think Google must think some of your titles are Spanish words might be worth putting them into Google translate to see what they mean.

Best Regards

Sam

**Comment by s3bubble** [comment]
Also, Gabor I would suggest installing this plugin it will help with image load speed.

https://en-gb.wordpress.org/plugins/force-regenerate-thumbnails/

Best Regards

Sam
