### ISSUE TITLE
Allow Widget areas and blog page template

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#32]
I'm using the plugin Multiple Themes Plugin https://wordpress.org/plugins/jonradio-multiple-themes/
so I can use some features you have not implemented yet, like blog templates, gallery, bbpress, and buddypress. 

The problem is I think Streamium is preventing Widgets to register. Can you add a option for a Widget area in a separate post type, like a blog post type or something?

I'd like to expand the Streamium to have a blog, and use BBpress and buddypress. I just need a simple page  template that would allow a sidebar or widget area.

This helps with SEO and building community around the video content.

**Comment by s3bubble** [comment]
Widgetized and bbpress will be added to the next release.

http://streamiumtheme.com/forums/
