### ISSUE TITLE
Movie Poster to "big"

### ISSUE THREAD

**Issue by bugsfilms** [s3bubble/Streamium-Netflix-Theme#34]
The Movie Poster is too big! I recommend a height of 300 and a width of 210 that fits for all covers. And for the title Expanded I recommend 33% more so a height of 400 and a width of 280 pixels.

**Comment by s3bubble** [comment]
With the latest pre-release you can set a number of tiles and you can also set if you want your
![screen shot 2017-08-02 at 18 10 54](https://user-images.githubusercontent.com/17534854/28885489-f9009120-77ad-11e7-9b12-28f7f0a4467d.png)
 poster to be landscape or portrait it will be a setting in the theme customizer styles.
