### ISSUE TITLE
Make theme follow Codex Guidelines (child theme support)

### ISSUE THREAD

**Issue by jpSimkins** [s3bubble/Streamium-Netflix-Theme#35]
This theme is great but without the ability to create a child theme from it, this theme is useless (well...requires too much work to customize) outside of S3Bubble. Which may or may not be what your want. Given that you open-sourced the theme, I would suggest you follow proper theme guidelines to allow for child theme development. Otherwise, this open-sourced project is really not what it seems.

**Comment by s3bubble** [comment]
Hi, @jpSimkins, the theme is only aimed at S3Bubble users it's not a free theme and will only work with one of the S3bubble packages GitHub is just a good place to store our releases.
