### ISSUE TITLE
I've tried to install the theme several times and get this error each time

### ISSUE THREAD

**Issue by shanenorman** [s3bubble/Streamium-Netflix-Theme#37]
Fatal error: Can't use function return value in write context in /home/content/28/13976228/html/network/wp-content/themes/Streamium-Netflix-Theme-12.0/inc/api/recent.php on line 71

**Comment by s3bubble** [comment]
The issue is the version of php you are running we have update the code to support old php versions can you please try the latest release.

**Comment by shanenorman** [comment]
Thank you! That is correct, I figured it out. I was running 5.4 and it needs to be at least 5.5 I believe
