### ISSUE TITLE
What is your license?

### ISSUE THREAD

**Issue by jpSimkins** [s3bubble/Streamium-Netflix-Theme#40]
This themes license is a puzzle. Your code states GPL v3 and then your readme file states:

```
Unauthorized use and/or duplication of this material without express and written permission from this site’s author and/or owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to S3Bubble and Streamium with appropriate and specific direction to the original content.
```

Your only enforceable license at this point is GPL v3 (in all your code) and this does not require permission of any kind to modify or distribute your code. Nor does it require any mention of S3Bubble.

Please fix your license and be aware of the version when you do because that's all that's enforceable.

**Comment by s3bubble** [comment]
Basically, the theme license is don't try and rip us of else we will hunt you down. Only joking but we will try our best. If you are using our theme for your own gain without asking us or paying for any version you are freeloading scumbag.

**Comment by jpSimkins** [comment]
Just wanted to bring this to your attention. Saying they are a freeloader is relative and a matter of debate given the opensource paradigm but to each their own. Just wanted to make you aware of this because I was going to use your theme for a project but the confusion with the license and the work to recode a bit of the project to adhere more to WordPress standards, I decided to start from scratch. Still, a great theme tho so good job :+1:
