### ISSUE TITLE
Disable Buttons & Logins

### ISSUE THREAD

**Issue by shanenorman** [s3bubble/Streamium-Netflix-Theme#41]
I am a paid Customer (Premium) and believe there should be toggles to disable/enable reviews and login as well as Facebook registration. I've attempted to do this in the code, but invariably end up breaking it. 

Can you please offer an option to toggle these features? At the moment, just like your demo site, doing simple things like reading reviews requires the user to be logged in.

**Comment by s3bubble** [comment]
@shanenorman we are adding these today.

**Comment by shanenorman** [comment]
Thanks!
