### ISSUE TITLE
Some questions (portrait/translation/more) 

### ISSUE THREAD

**Issue by silvioghedin** [s3bubble/Streamium-Netflix-Theme#42]
Hello, I'll test the trial, I wanna make some questions:

1) Is possible to select some categories to appear the portrait options?

2) Can I make the site multi-lingual? Can I change the thumbnail for each language? And Its possible to loads the video with the subtitle which corresponds to its language?

3) If I watch 30% of the video, it shows a bar with the porcentage like netflix?

**Comment by silvioghedin** [comment]
Nothing???

**Comment by s3bubble** [comment]
Apologies.

Q: Is possible to select some categories to appear the portrait options?
A: We are not likely to implement this

Q: Can I make the site multi-lingual? Can I change the thumbnail for each language? And Its possible to loads the video with the subtitle which corresponds to its language?
A: The theme should already work with a multilingual plugin.

Q: If I watch 30% of the video, it shows a bar with the porcentage like netflix?
A: It already does this but the percentage shows inside the tile. 

See here http://streamiumtheme.com/ login and watch a video it will then appear in recently watched with the percentage.

**Comment by silvioghedin** [comment]
Thanks, one more thing, I need to scroll down to see the player of the video, could you fix this?

I'll sign the premium plan, i'll make more test before it.

Thanks a lot.

PS: It's not translating to portuguese :/
