### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by shanenorman** [s3bubble/Streamium-Netflix-Theme#43]
For some reason, thumbnails are not appearing. I also see this on your demo site and others. 

http://codeblacknetwork.com

**Comment by shanenorman** [comment]
For some strange reason, the thumbnails don't appear on the site.

**Comment by s3bubble** [comment]
Hi @shanenorman,

We see you thumbnails did this happen briefly after an update it was probably cached?

**Comment by s3bubble** [comment]
I think we see what the issue could be running a fix.

**Comment by shanenorman** [comment]
Fantastic. It seems to happen randomly and most often on Chrome. Thank you for your help!

**Comment by s3bubble** [comment]
We have pushed the new update, please install the latest version.

Under customizer in site identity, you can also disable login and set the player to show social buttons on all videos.

**Comment by s3bubble** [comment]
Hi Shanem



You may need to re install one more time to get the latest tested version.



Best Regards



Sam



Samuel S3Bubble Team Leader



Our working hours are 9am - 5pm Greenwich Mean Time London please only expect a response within these times.



Useful links


Streamium Theme Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JDIkxLv9ryCFX7LzXDD6QM2

Latest Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JCYQPTM7fDktQgbVEJEonbl


s3bubble.com










---- On Fri, 13 Oct 2017 18:05:58 +0000 shanenorman &lt;notifications@github.com&gt; wrote ----




Closed #43.
