### ISSUE TITLE
Fix Translation + padding left and header color

### ISSUE THREAD

**Issue by silvioghedin** [s3bubble/Streamium-Netflix-Theme#45]
- There are some texts that is not possible to translate, can you take a look to fix this? http://prntscr.com/h02isd

- Can you make a option to make header transparent and remove the padding left on the movies? http://prntscr.com/h02j09

- I talked with someone on the chat, to fix the height of the videos, you have to scroll down to see the player.

Thanks guys, the theme is amazing keep going ;)

**Comment by s3bubble** [comment]
Translation updates have been push into this new tag release update to get the latest.

https://github.com/s3bubble/Streamium-Netflix-Theme/releases/tag/17.25

We won't be doing this one might be worth doing this yourself in a child stylesheet.
~~~
Can you make a option to make header transparent and remove the padding left on the movies? 
~~~

Height of the video is also fixed
