### ISSUE TITLE
Scroll problem on tablet and phones

### ISSUE THREAD

**Issue by devahmadmohammadi** [s3bubble/Streamium-Netflix-Theme#49]
when I use the website on my phone and try to scroll down or up I will have to touch the empty spaces between the movie posters to work properly and if I try to scroll down or up from anywhere else it will not work is there a way to fix this problem?

**Comment by s3bubble** [comment]
Fixed with latest version

**Comment by devahmadmohammadi** [comment]
This problem has not yet been resolved as I have checked on multiple
devices, I would appreciate it if you could fix it ASAP

**Comment by devahmadmohammadi** [comment]
Hi

I have been contacting AWS for the past few weeks for a problem that they
believe has occurred from your end.

I have submitted 60 videos throw bulk action for encoding and it seems like
the amount of submissions were  635 rows inclusive of the headers as they
have mentioned in this forwarded email.

They have charged me over 1500 USD which was beyond my allocated budget of
600 USD for the amount of 60 videos. they are trying to resolve this
problem but i need your help to know what i should do to fix this problem
and take my account out of suspension.

---------- Forwarded message ----------
From: anashid islami <anashid2anashid@gmail.com>
Date: Wed, Apr 18, 2018 at 1:27 PM
Subject: Fwd: [CASE 4911506341] unsuspected charges
To: devahmadmohammadi@gmail.com



---------- Forwarded message ---------
From: no-reply-aws@amazon.com <no-reply-aws@amazon.com>
Date: Wed, 18 Apr 2018, 13:25
Subject: RE:[CASE 4911506341] unsuspected charges
To: anashid2anashid@gmail.com <anashid2anashid@gmail.com>



Hello,

I trust my email finds you well.

Thank you so much for your patience while I actively worked with the
Service Teams.

The following feedback has been provided:

=> Please find attached a record of completed jobs for this account for
March 2018.

=> This file has 635 rows inclusive of the headers. This corresponds to a
job output which is our unit for billing.

=> The screen shot you've provided suggests that you manage your account
exclusively through a 3rd party service. This incident could be related to
3rd party service's actions on your behalf.

I hope the above information is useful, but please let us know if you have
any further queries or concerns. We are always here for you and happy to
help where we can.

Have a lovely day further!

To see the file named 'Case ID - 4911506341.xlsx' included with this
correspondence, please use the case link given below the signature.

Best regards,

Megan E.
Amazon Web Services

Check out the AWS Support Knowledge Center, a knowledge base of articles
and videos that answer customer questions about AWS services:
https://aws.amazon.com/premiumsupport/knowledge-
center/?icmpid=support_email_category

We value your feedback. Please rate my response using the link below.
===================================================

To contact us again about this case, please return to the AWS Support
Center using the following URL:

https://console.aws.amazon.com/support/home#/case/?
displayId=4911506341&language=en

(If you are connecting by federation, log in before following the link.)

*Please note: this e-mail was sent from an address that cannot accept
incoming e-mail. Please use the link above if you need to contact us again
about this same issue.

====================================================================
Learn to work with the AWS Cloud. Get started with free online videos and
self-paced labs at
http://aws.amazon.com/training/
====================================================================

Amazon Web Services, Inc. and affiliates

**Comment by devahmadmohammadi** [comment]
i have just noticed that video trailers have been disabled is this
something that you have done or its a setting tweak?

**Comment by devahmadmohammadi** [comment]
hi would you please reply to this email

i have just noticed that video trailers have been disabled is this
something that you have done or its a setting tweak?

there is a second problem : there is no interface showing on the first page

**Comment by s3bubble** [comment]
Hi @devahmadmohammadi 

We haven't changed anything regarding trailers they are still active on our theme https://streamiumtheme.com

Have you changed anything or added any plugins?

Best Regards

Sam

**Comment by devahmadmohammadi** [comment]
no i have not changed anything.it was working yesterday and today it dosent
show up at all

**Comment by s3bubble** [comment]
@devahmadmohammadi we have no way of changing your setup so not sure how it has changed we have the latest version of WordPress we are testing with.

Do you have a link set for the trailer within your admin?

Can you send us a link to your website send here or send to support@s3bubble.com

Thanks
