### ISSUE TITLE
Add Slick Slider Admin panel to WP Admin area

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#5]
I would like to be able to have more control over the Slick Slider plugin in the dist folder. Can you add the admin  panel for the plugin https://maxgalleria.com/downloads/slick-slider-for-wordpress/ to the theme if you are installing the plugin and maybe disable the option for selecting images. There are some options i'd like to use without changing the code, such as Lazy Load, which is very useful.

**Comment by s3bubble** [comment]
we wont be doing this
