### ISSUE TITLE
using ffmpeg on pc to encode 

### ISSUE THREAD

**Issue by flix8918** [s3bubble/Streamium-Netflix-Theme#51]
hello, i downloaded and installed ffmpeg on my pc, and i used the command prompt on window 10 to test it and it works, i have been searching for a code to use with ffmpeg to encode to m3u8 and used the one from HLS-Stream-Creator but i am missing things, i did watch your video about using ffmpeg but it was for a mac and i couldn't follow up and use it.

please do you have a code i can use or instructions on how to use it with a pc.

thank you

**Comment by s3bubble** [comment]
Hi @flix8918

Unfortunately, we do not have a video explaining how to do this on windows yet I am going to close this because it is more related to video encoding instead of the theme.
