### ISSUE TITLE
Draft posts appear in search results

### ISSUE THREAD

**Issue by BrianHenryIE** [s3bubble/Streamium-Netflix-Theme#57]
It seems all posts, not just published posts, appear in search results. The draft posts don't appear in the homepage videos; I didn't check in the categories.

I think the fix is to add `'post_status' => 'publish'` into the `WP_Query`s in `/inc/api/search.php`, though I remedied this for our site by just deleting videos that should be hidden.

**Comment by jdphiladelphia** [comment]
In a similar vein, movie posts show up no matter the status.  There is no way to hide a movie unless we delete its post altogether.  Movies should not appear publicly unless they are in the PUBLISHED status.

Respectfully,
JD

**Comment by s3bubble** [comment]
Thanks for the info this is fixed and will be in the next release
