### ISSUE TITLE
Redundant requests to update streamium_create_resume when paused

### ISSUE THREAD

**Issue by BrianHenryIE** [s3bubble/Streamium-Netflix-Theme#58]
As I'm debugging, I see a request every second to `admin-ajax.php` updating `streamium_create_resume`, e.g. `POST` `action=streamium_create_resume&percentage=3&post_id=8786&nonce=a88788ecaa`. 

I have the video paused, i.e. the percentage is never changing and each request is identical, so this is a waste of resources on both sides of the connection. We have had users comment on the speed of our video site so it would be nice to address that in every way possible. Also, all the network requests make things harder to debug.

**Comment by s3bubble** [comment]
Hi @BrianHenryIE 

Yes, thanks for highlighting this it is something we are looking into with the next release we are really focusing on speed.

Just as an update to highlight our development cycle.

1. We have fully updated our player with themes and lots of bug fixes and framework updates which is pending a full release.
2. Our api has been fully updated and is pending a release.
3. The dashboard has been updated and released. 

When the api and player are fully released it really frees up our time to fully focus on the theme which is what we have been working towards.

So we appreciate the info and updates keep it coming.

Best Regards

Sam

**Comment by s3bubble** [comment]
This is fixed and will be available in the next release
