### ISSUE TITLE
Published Date

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/Streamium-Netflix-Theme#59]
Greetings S3Bubble,

Thank you for such a great theme. On the website I'm managing, there is a need to promote upcoming studio trailers (see www.flixpics.com). These are movies that have not yet released.

However, the "Release Date" of each movie on the Streamium Theme is set to match the published date of the post.  In our use case, we need a way to set a different date, as the Release Date is never the Published Date of the post.

If we edit the Post Date to the correct release date, this is a problem for future release dates, since the post becomes a "Scheduled" post to auto-publish on the future date (which is WordPress behaving as designed).

Can you consider our use case?

Respectfully submitted,
JD

**Comment by s3bubble** [comment]
Hi JD,

We are moving the release date into its own meta box see the pre-release.

Thanks
