### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/Streamium-Netflix-Theme#64]
Dear S3 Bubble,

The Change Log posted on GitHub for the Streamium Theme is very helpful, thank you!

Going forward, can you guys also provide the version, date and category (FIX OR FEATURE) for each item listed? That would be super helpful.

Below are some examples of what I am describing:

https://github.com/woocommerce/woocommerce/releases

https://github.com/cabrerahector/wordpress-popular-posts/blob/master/changelog.md

https://github.com/skywinder/github-changelog-generator/blob/master/CHANGELOG.md

https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

http://keepachangelog.com/en/1.0.0/

Respectfully submitted,
JD

**Comment by s3bubble** [comment]
Hi JD,

Thanks for the suggestion we will be adding changelog in our releases and pre release going forward.

https://github.com/s3bubble/Streamium-Netflix-Theme/releases
