### ISSUE TITLE
Improve performance of index page query

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#7]
If a site has many posts, then too many are loaded to the main page, making the page slow. For example, I have a site with over 300 posts with Featured Images and the index pages, fetches 184 posts to load the page. This is far too many.

Furthermore, the query does not select the proper thumbnail size, it selects the full size image and them resizes, so this is tremendously ineffiecient. My index page is loading 30MB because the theme is not actually choosing the correct thumbnail per the slick slider size. I can provide examples.

**Comment by s3bubble** [comment]
Now page navigation has been implemented this can be set within.

Settings -> Reading

Blog pages show at most
