### ISSUE TITLE
HLS STreaming Encoding

### ISSUE THREAD

**Issue by DrStupit** [s3bubble/Streamium-Netflix-Theme#75]
Hi Guys 

Im having an issue, with the delivery of video media. Im encoding using the s3 preset formats given. 

And as off the last 2 weeks, give or take, the streaming has become extremely slow. 

Previously, I was able to stream a full 24 minute length show on a 1.5mb line. 

Now every 10 seconds, the video (same video) is buffering. 

When i dug deeper, and went into developer tools, and monitored the network with regard to the encoded ts files being sent, a 1.5mb part is taking up to 20s to load. 

Have their been any updates, or AWS cloudfront servers gone down? 

Kind Regards 
Kerev

**Comment by s3bubble** [comment]
Hi Kerev,

We are not aware of any issue maybe try contact AWS directly as this seems to be directly related to CloudFront as soon as the master playlist is delivered via the api then the browser takes over with requests directly from Cloudfront.

You can try clearing you CloudFront cache.

Go to the dashboard click actions on your distribution and then clear cache.

Best Regards

Sam

**Comment by DrStupit** [comment]
Thank you for the response. I will try clearing the cache on the AWS dashboard.
