### ISSUE TITLE
Search Results Not Showing Series

### ISSUE THREAD

**Issue by Samaxx** [s3bubble/Streamium-Netflix-Theme#78]
When searching, no TV Series or video series are shown.

**Comment by s3bubble** [comment]
Hi @Samaxx 

Can you send us an example it searches series on the Streamium theme 

https://streamiumtheme.com/?s=youtube

Do you mean individual videos within a series?

**Comment by Samaxx** [comment]
When searching https://streamiumtheme.com/?s=dunkirk the trailer comes up but not the actual episode found here: https://streamiumtheme.com/tv/the-good-place-tv-series/?v=1

**Comment by s3bubble** [comment]
Hi @Samaxx 

The search will not search individual episodes within a series only the main series.

for instance, searching https://streamiumtheme.com/?s=the+good+place

Will return the series.
