### ISSUE TITLE
Staging Server Environment - Handling License

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/Streamium-Netflix-Theme#79]
Dear S3Bubble,

I love the latest updates to the theme, thank you!

How are others handling staging or development server environments? In terms of the license?

It's hard to preview some features on the staging server since the Streamium Theme License only works on a single website, the one in production. This defeats the purpose at times since we nor the client can preview how something will really behave until it is put on the live production site.

Is it possible to somehow let S3Bubble know that it's the same site, so that S3Bubble will fully work in the two different environments for the same website?

Thinking out loud,
JD

**Comment by s3bubble** [comment]
Hi JD,

Just drop us an email and let us know your staging url and we can allow that for you in your account.

**Comment by s3bubble** [comment]
Hi JD,

We have added these for you.
