### ISSUE TITLE
Drafted & Pending Movie Posts Show in Directory

### ISSUE THREAD

**Issue by jdphiladelphia** [s3bubble/Streamium-Netflix-Theme#88]
Dear S3Bubble,

Movie posts with a STATUS set to DRAFT or PENDING show on the directory page. They should only show if the status is set to PUBLISHED.

We need a way to temporary HIDE movies from the movie directory without DELETING it altogether. 

We have the latest version of the Streamium Theme (and this is also an issue in earlier versions).

Regards,
JD

**Comment by s3bubble** [comment]
Update pushed to pre release
