### ISSUE TITLE
Separate the setting "Blog pages show at most" from the category page

### ISSUE THREAD

**Issue by wenotice** [s3bubble/Streamium-Netflix-Theme#9]
This setting limits the number of posts in the category pages and the category pages does not give an option for pagination or lazy load. I would prefer to have a pagination option on the category page. 

For example, I have 99 posts in a category but I can only show the limited amount per the option and can't get the the remaining.

**Comment by s3bubble** [comment]
Now page navigation has been implemented this can be set within.

Settings -> Reading 

Blog pages show at most
