### ISSUE TITLE
YouTube videos not playing on mobile view 

### ISSUE THREAD

**Issue by Jasonp2017** [s3bubble/Streamium-Netflix-Theme#96]
## Description
Unable to load/play videos when on a mobile device and the video source is YouTube. 

If you visit the following link you will find it plays fine when on a desktop/laptop browser (but not on a mobile device) - 

http://prahamovies.co.uk/index.php/movie/gullivers-travels/

No other issue currently. Please respond asap.

**Comment by s3bubble** [comment]
@Jasonp2017 

We cannot provide support on websites with copyright material.

**Comment by Jasonp2017** [comment]
How do you mean copyright material? that link is from youtube?

**Comment by Jasonp2017** [comment]
@s3bubble
